Handle symbols in `(:require ...)`
Eg: `boot-reload` generates the following file
if it's used with the `:on-jsload 'app.main/index` option:
```
(ns adzerk.boot-reload.init4782 (:require [adzerk.boot-reload.client :as client] app.main))
(client/connect "ws://localhost:63061" {:ws-host nil, :asset-host nil, :on-jsload (fn* [] (app.main/index))})⏎
```
and since `app.main` is not in a vector we get an exception from `first`:
```
java.lang.IllegalArgumentException: Don't know how to create ISeq from: clojure.lang.Symbol
```